local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>psf', builtin.find_files, {})
vim.keymap.set('n', '<leader>psg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>psb', builtin.buffers, {})
vim.keymap.set('n', '<leader>psh', builtin.help_tags, {})
